[package]
org = "dilantha"
name = "news_user_api"
version = "0.1.0"
distribution = "2201.8.6"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.2.20"